$(document).ready(function () {
    if(document.getElementById("Programador") !== null)
    document.getElementById("Programador").innerHTML = '<ul>'
                + '<li>'
                + '    <a href="Inicio">'
                + '        <i class="fas fa-home"></i>'
                + '        <span class="nav-text">'
                + '            Inicio'
                + '        </span>'
                + '    </a>'
                + '</li>'
                + '<li class="has-subnav">'
                + '    <a href="MenuPacientes">'
                + '        <i class="far fa-user-circle"></i>'
                + '        <span class="nav-text">'
                + '            Menú Pacientes'
                + '        </span>'
                + '   </a>'
                + '</li>'
                + '<li class="has-subnav">'
                + '    <a href="MenuMedicos">'
                + '       <i class="fas fa-user-md"></i>'
                + '        <span class="nav-text">'
                + '            Menú Medicos'
                + '        </span>'
                + '    </a>'
                + '</li>'
                + '<li class="has-subnav">'
                + '    <a href="MenuEmpleados">'
                + '        <i class="fas fa-users"></i>'
                + '        <span class="nav-text">'
                + '            Menú Personal'
                + '        </span>'
                + '    </a>'
                + '</li>'
                + '<li>'
                + '    <a href="MenuVacaciones">'
                + '        <i class="fas fa-luggage-cart"></i>'
                + '        <span class="nav-text">'
                + '            Menú Vacaciones'
                + '        </span>'
                + '    </a>'
                + '</li>'
                + '<li>'
                + '    <a href="MenuCitas">'
                + '        <i class="fas fa-book-medical"></i>'
                + '        <span class="nav-text">'
                + '            Menú Citas'
                + '        </span>'
                + '   </a>'
                + '</li>'
            + '</ul>'
            + '<ul class="logout">'
                + '<li>'
                + '    <a href="Inicio?accion=Logout">'
                + '        <i class="fas fa-power-off"></i>'
                + '        <span class="nav-text">'
                + '            Cerrar Sesión'
                + '        </span>'
                + '    </a>'
                + '</li>'
            + '</ul>';
            
            if(document.getElementById("Administrador") !== null)
            document.getElementById("Administrador").innerHTML = '<ul>'
                + '<li>'
                + '    <a href="Inicio">'
                + '        <i class="fas fa-home"></i>'
                + '        <span class="nav-text">'
                + '            Inicio'
                + '        </span>'
                + '    </a>'
                + '</li>'
                + '<li class="has-subnav">'
                + '    <a href="MenuPacientes">'
                + '        <i class="far fa-user-circle"></i>'
                + '        <span class="nav-text">'
                + '            Menú Pacientes'
                + '        </span>'
                + '   </a>'
                + '</li>'
                + '<li class="has-subnav">'
                + '    <a href="MenuMedicos">'
                + '       <i class="fas fa-user-md"></i>'
                + '        <span class="nav-text">'
                + '            Menú Medicos'
                + '        </span>'
                + '    </a>'
                + '</li>'
                + '<li class="has-subnav">'
                + '    <a href="MenuEmpleados">'
                + '        <i class="fas fa-users"></i>'
                + '        <span class="nav-text">'
                + '            Menú Personal'
                + '        </span>'
                + '    </a>'
                + '</li>'
                + '<li>'
                + '    <a href="MenuVacaciones">'
                + '        <i class="fas fa-luggage-cart"></i>'
                + '        <span class="nav-text">'
                + '            Menú Vacaciones'
                + '        </span>'
                + '    </a>'
                + '</li>'
                + '<li>'
                + '    <a href="MenuCitas">'
                + '        <i class="fas fa-book-medical"></i>'
                + '        <span class="nav-text">'
                + '            Menú Citas'
                + '        </span>'
                + '   </a>'
                + '</li>'
            + '</ul>'
            + '<ul class="logout">'
                + '<li>'
                + '    <a href="Inicio?accion=Logout">'
                + '        <i class="fas fa-power-off"></i>'
                + '        <span class="nav-text">'
                + '            Cerrar Sesión'
                + '        </span>'
                + '    </a>'
                + '</li>'
            + '</ul>';
   
});
